# Generated by Django 5.2.11 on 2026-02-13 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('maturity_days', models.PositiveIntegerField(default=60)),
                ('spacing_cm', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompostBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateField()),
                ('method', models.CharField(default='3-bay', max_length=80)),
                ('inputs', models.TextField(blank=True)),
                ('moisture_check', models.CharField(blank=True, max_length=80)),
                ('turned_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=40)),
                ('estimated_qty_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=40)),
                ('target_yield_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organic.crop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_on', models.DateField()),
                ('operation_type', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='organic.cropcycle')),
                ('labourer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvested_on', models.DateField()),
                ('qty_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade', models.CharField(blank=True, max_length=60)),
                ('losses_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organic.cropcycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_on', models.DateField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=80)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organic.cropcycle')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PestDiseaseIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_on', models.DateField()),
                ('type', models.CharField(max_length=120)),
                ('severity', models.CharField(default='medium', max_length=40)),
                ('action_taken', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organic.cropcycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('area_acres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('soil_type', models.CharField(blank=True, max_length=80)),
                ('irrigation', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organic.plot'),
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_on', models.DateField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ec', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('phosphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('organic_matter_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organic.plot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
