# Generated by Django 5.2.11 on 2026-02-13 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('propagation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurserySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('shade_net', models.BooleanField(default=True)),
                ('water_source', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrayBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_name', models.CharField(max_length=120)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('started_on', models.DateField()),
                ('trays_count', models.PositiveIntegerField(default=0)),
                ('cells_per_tray', models.PositiveIntegerField(default=128)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='active', max_length=40)),
                ('seed_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='propagation.seedlot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.nurserysite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransplantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('transplanted_count', models.PositiveIntegerField(default=0)),
                ('destination', models.CharField(blank=True, max_length=160)),
                ('supervised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.traybatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeedlingLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('lost_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(max_length=160)),
                ('action_taken', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.traybatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NurseryDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('watered', models.BooleanField(default=False)),
                ('fertilizer_applied', models.BooleanField(default=False)),
                ('pest_observed', models.BooleanField(default=False)),
                ('disease_observed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.traybatch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
