# Generated by Django 3.2.9 on 2022-05-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="numbers",
            new_name="phone_numbers",
        ),
    ]
