# Generated by Django 5.2.11 on 2026-02-13 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('forage_notes', models.TextField(blank=True)),
                ('water_source', models.CharField(blank=True, max_length=120)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hive_type', models.CharField(default='langstroth', max_length=60)),
                ('hive_code', models.CharField(max_length=80)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=40)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beekeeping.apiary')),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvested_on', models.DateField()),
                ('honey_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wax_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=60)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beekeeping.hive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('feed_type', models.CharField(max_length=80)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beekeeping.hive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiveInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('queen_seen', models.BooleanField(default=False)),
                ('brood_present', models.BooleanField(default=False)),
                ('honey_frames', models.PositiveIntegerField(default=0)),
                ('pests', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beekeeping.hive')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
