# Generated by Django 5.2.11 on 2026-02-13 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_name', models.CharField(max_length=120)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('lot_code', models.CharField(blank=True, max_length=80)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('seed_count_est', models.PositiveIntegerField(default=0)),
                ('storage_notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GerminationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_on', models.DateField()),
                ('sample_size', models.PositiveIntegerField(default=100)),
                ('germinated', models.PositiveIntegerField(default=0)),
                ('days_to_emerge', models.PositiveIntegerField(default=0)),
                ('medium', models.CharField(blank=True, max_length=80)),
                ('seed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propagation.seedlot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeedTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treated_on', models.DateField()),
                ('treatment_type', models.CharField(max_length=120)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('seed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propagation.seedlot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
