# Generated by Django 5.2.11 on 2026-02-13 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedPlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planted_on', models.DateField()),
                ('method', models.CharField(blank=True, max_length=80)),
                ('spacing', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='active', max_length=40)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organic.crop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvested_on', models.DateField()),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen_garden.bedplanting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GardenBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('length_m', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('width_m', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('sunlight', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bedplanting',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen_garden.gardenbed'),
        ),
    ]
