# Generated by Django 5.2.11 on 2026-02-13 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock_type', models.CharField(choices=[('broiler', 'Broiler'), ('layer', 'Layer'), ('kienyeji', 'Kienyeji')], max_length=40)),
                ('batch_code', models.CharField(max_length=80)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('initial_count', models.PositiveIntegerField()),
                ('current_count', models.PositiveIntegerField()),
                ('status', models.CharField(default='active', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=60)),
                ('start_day', models.PositiveIntegerField(default=1)),
                ('end_day', models.PositiveIntegerField(default=14)),
                ('target_fcr', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('feed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('eggs_count', models.PositiveIntegerField(default=0)),
                ('cracked', models.PositiveIntegerField(default=0)),
                ('trays', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('culled', models.PositiveIntegerField(default=0)),
                ('avg_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('water_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('symptoms', models.TextField()),
                ('suspected_diagnosis', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(default='medium', max_length=40)),
                ('action_taken', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoultryHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('capacity_birds', models.PositiveIntegerField(default=0)),
                ('ventilation', models.CharField(blank=True, max_length=120)),
                ('bedding_type', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='flock',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poultry.poultryhouse'),
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=80)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer', models.CharField(blank=True, max_length=140)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('vaccine_name', models.CharField(max_length=120)),
                ('route', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
